### ISSUE TITLE
Failed building wheel for kiwisolver

### ISSUE THREAD

**Issue by SamuelXiao** [MikeBirdTech/open-interpreter-termux#15]
When I installed required packages using the following commad:
  ` yes | pkg install termux-api python-pip cmake ninja patchelf build-essential matplotlib rust binutils libzmq`

the error happened:

Building wheels for collected packages: kiwisolver
  Building wheel for kiwisolver (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for kiwisolver (pyproject.toml) did not run successfully.                            │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build                                      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/kiwisolver
      copying py/kiwisolver/__init__.py -> build/lib.linux-aarch64-cpython-311/kiwisolver
      copying py/kiwisolver/exceptions.py -> build/lib.linux-aarch64-cpython-311/kiwisolver                 copying py/kiwisolver/_cext.pyi -> build/lib.linux-aarch64-cpython-311/kiwisolver
      copying py/kiwisolver/py.typed -> build/lib.linux-aarch64-cpython-311/kiwisolver
      running build_ext
      building 'kiwisolver._cext' extension              creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/py                                                      creating build/temp.linux-aarch64-cpython-311/py/src
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/constraint.cpp -o build/temp.linux-aarch64-cpython-311/py/src/constraint.o -std=c++11
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/expression.cpp -o build/temp.linux-aarch64-cpython-311/py/src/expression.o -std=c++11
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/kiwisolver.cpp -o build/temp.linux-aarch64-cpython-311/py/src/kiwisolver.o -std=c++11
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/solver.cpp -o build/temp.linux-aarch64-cpython-311/py/src/solver.o -std=c++11
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/strength.cpp -o build/temp.linux-aarch64-cpython-311/py/src/strength.o -std=c++11
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/term.cpp -o build/temp.linux-aarch64-cpython-311/py/src/term.o -std=c++11
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/tmp/pip-build-env-ibn0lych/overlay/lib/python3.11/site-packages/cppy/include -I. -I/data/data/com.termux/files/usr/include/python3.11 -c py/src/variable.cpp -o build/temp.linux-aarch64-cpython-311/py/src/variable.o -std=c++11
      aarch64-linux-android-clang++ -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib build/temp.linux-aarch64-cpython-311/py/src/constraint.o build/temp.linux-aarch64-cpython-311/py/src/expression.o build/temp.linux-aarch64-cpython-311/py/src/kiwisolver.o build/temp.linux-aarch64-cpython-311/py/src/solver.o build/temp.linux-aarch64-cpython-311/py/src/strength.o build/temp.linux-aarch64-cpython-311/py/src/term.o build/temp.linux-aarch64-cpython-311/py/src/variable.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-aarch64-cpython-311/kiwisolver/_cext.cpython-311.so
      aarch64-linux-android-clang++: error: unknown argument: '-fno-openmp-implicit-rpath'
      aarch64-linux-android-clang++: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kiwisolver
Failed to build kiwisolver                         ERROR: Could not build wheels for kiwisolver, which is required to install pyproject.toml-based projects
dpkg: error processing package matplotlib (--configure):
 installed matplotlib package post-installation script subprocess returned error exit status 1        Errors were encountered while processing:
 matplotlib
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)                    
yes: standard output: Broken pipe

**Comment by okineadev** [comment]
Run this command:

```bash
_file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
rm -rf $PREFIX/lib/python3.11/__pycache__
cp $_file "$_file".backup
sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
```

See https://github.com/termux/termux-packages/issues/20039#issuecomment-2096494418

**Comment by SamuelXiao** [comment]
Thanks! It is fixed and open-interpreter has been installed. But when I run it, the error encountered: 

![Screenshot_20240521_104428_com termux](https://github.com/MikeBirdTech/open-interpreter-termux/assets/10758773/f4cbe659-2933-45fd-86fc-35a8ca24d9e8)

**Comment by okineadev** [comment]
> Thanks! It is fixed and open-interpreter has been installed. But when I run it, the error encountered: 
> 
> ![Screenshot_20240521_104428_com termux](https://github.com/MikeBirdTech/open-interpreter-termux/assets/10758773/f4cbe659-2933-45fd-86fc-35a8ca24d9e8)
> 

Run this command:

```bash
patchelf --add-needed libpython3.11.so "/data/data/com.termux/files/usr/lib/python3.11/site-packages/zmq/backend/cython/_zmq.cpython-311.so"
```

After that, close all sessions in **Termux** and then try to install `open-interpreter`

---

Source: https://www.reddit.com/r/termux/comments/15rl58e/running_into_issues_with_pysr_module_in_python/

**Comment by SamuelXiao** [comment]
Done! Thank you!

**Comment by okineadev** [comment]
That's good. If anything you can also run **ollama** locally in **Termux**
